#include "cly.h"
const char rt_src_linux[] =
    "bits 32\n"
    "section .text\n"
    "__cly_syscall:\n"
    "    push ebx\n"
    "    push ecx\n"
    "    push esi\n"
    "    push edi\n"
    "    push ebp\n"
    "    cmp eax, __cly_nsys\n"
    "    jae .bad\n"
    "    movzx eax, word [__cly_sysmap+eax*2]\n"
    "    cmp eax, 0xFFFF\n"
    "    je .bad\n"
    "    mov ebx, edi\n"
    "    mov ecx, esi\n"
    "    mov esi, [__cly_vregs+8]\n"
    "    mov ebp, [__cly_vregs+4]\n"
    "    mov edi, [__cly_vregs]\n"
    "    cmp eax, 192\n"
    "    jne .go\n"
    "    shr ebp, 12\n"
    ".go:\n"
    "    int 0x80\n"
    "    jmp .out\n"
    ".bad:\n"
    "    mov eax, -38\n"
    ".out:\n"
    "    pop ebp\n"
    "    pop edi\n"
    "    pop esi\n"
    "    pop ecx\n"
    "    pop ebx\n"
    "    ret\n"
;
const char rt_src_win[] =
    "bits 32\n"
    "import __imp_GetStdHandle kernel32.dll GetStdHandle\n"
    "import __imp_WriteFile kernel32.dll WriteFile\n"
    "import __imp_ReadFile kernel32.dll ReadFile\n"
    "import __imp_CreateFileA kernel32.dll CreateFileA\n"
    "import __imp_CloseHandle kernel32.dll CloseHandle\n"
    "import __imp_SetFilePointer kernel32.dll SetFilePointer\n"
    "import __imp_VirtualAlloc kernel32.dll VirtualAlloc\n"
    "import __imp_VirtualFree kernel32.dll VirtualFree\n"
    "import __imp_ExitProcess kernel32.dll ExitProcess\n"
    "import __imp_GetCurrentProcessId kernel32.dll GetCurrentProcessId\n"
    "import __imp_Sleep kernel32.dll Sleep\n"
    "import __imp_GetSystemTimeAsFileTime kernel32.dll GetSystemTimeAsFileTime\n"
    "import __imp_DeleteFileA kernel32.dll DeleteFileA\n"
    "import __imp_CreateDirectoryA kernel32.dll CreateDirectoryA\n"
    "import __imp_RemoveDirectoryA kernel32.dll RemoveDirectoryA\n"
    "import __imp_GetCurrentDirectoryA kernel32.dll GetCurrentDirectoryA\n"
    "import __imp_SetCurrentDirectoryA kernel32.dll SetCurrentDirectoryA\n"
    "section .data\n"
    "__cly_brk dd 0\n"
    "__cly_brkbase dd 0\n"
    "__cly_brkcom dd 0\n"
    "section .text\n"
    "__cly_h:\n"
    "    cmp edi, 2\n"
    "    ja .raw\n"
    "    mov eax, -10\n"
    "    sub eax, edi\n"
    "    push eax\n"
    "    call [__imp_GetStdHandle]\n"
    "    ret\n"
    ".raw:\n"
    "    mov eax, edi\n"
    "    ret\n"
    "__cly_ft:\n"
    "    sub esp, 8\n"
    "    push esp\n"
    "    call [__imp_GetSystemTimeAsFileTime]\n"
    "    pop eax\n"
    "    pop edx\n"
    "    sub eax, 0xD53E8000\n"
    "    sbb edx, 0x019DB1DE\n"
    "    mov ecx, 10000000\n"
    "    div ecx\n"
    "    ret\n"
    "__cly_syscall:\n"
    "    push ebx\n"
    "    push ecx\n"
    "    push edx\n"
    "    push esi\n"
    "    push edi\n"
    "    push ebp\n"
    "    cmp eax, 0\n"
    "    je .read\n"
    "    cmp eax, 1\n"
    "    je .write\n"
    "    cmp eax, 2\n"
    "    je .open\n"
    "    cmp eax, 3\n"
    "    je .close\n"
    "    cmp eax, 8\n"
    "    je .lseek\n"
    "    cmp eax, 9\n"
    "    je .mmap\n"
    "    cmp eax, 11\n"
    "    je .munmap\n"
    "    cmp eax, 12\n"
    "    je .brk\n"
    "    cmp eax, 16\n"
    "    je .notty\n"
    "    cmp eax, 24\n"
    "    je .yield\n"
    "    cmp eax, 35\n"
    "    je .nanosleep\n"
    "    cmp eax, 39\n"
    "    je .getpid\n"
    "    cmp eax, 60\n"
    "    je .exit\n"
    "    cmp eax, 79\n"
    "    je .getcwd\n"
    "    cmp eax, 80\n"
    "    je .chdir\n"
    "    cmp eax, 83\n"
    "    je .mkdir\n"
    "    cmp eax, 84\n"
    "    je .rmdir\n"
    "    cmp eax, 87\n"
    "    je .unlink\n"
    "    cmp eax, 96\n"
    "    je .gtod\n"
    "    cmp eax, 102\n"
    "    je .zero\n"
    "    cmp eax, 104\n"
    "    je .zero\n"
    "    cmp eax, 107\n"
    "    je .zero\n"
    "    cmp eax, 108\n"
    "    je .zero\n"
    "    cmp eax, 201\n"
    "    je .time\n"
    "    cmp eax, 228\n"
    "    je .cgt\n"
    "    cmp eax, 231\n"
    "    je .exit\n"
    "    mov eax, -38\n"
    "    jmp .out\n"
    ".zero:\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".notty:\n"
    "    mov eax, -25\n"
    "    jmp .out\n"
    ".eio:\n"
    "    mov eax, -5\n"
    "    jmp .out\n"
    ".enoent:\n"
    "    mov eax, -2\n"
    "    jmp .out\n"
    ".read:\n"
    "    mov ebx, edx\n"
    "    call __cly_h\n"
    "    sub esp, 4\n"
    "    push 0\n"
    "    lea ecx, [esp+4]\n"
    "    push ecx\n"
    "    push ebx\n"
    "    push esi\n"
    "    push eax\n"
    "    call [__imp_ReadFile]\n"
    "    pop ecx\n"
    "    test eax, eax\n"
    "    jz .eio\n"
    "    mov eax, ecx\n"
    "    jmp .out\n"
    ".write:\n"
    "    mov ebx, edx\n"
    "    call __cly_h\n"
    "    sub esp, 4\n"
    "    push 0\n"
    "    lea ecx, [esp+4]\n"
    "    push ecx\n"
    "    push ebx\n"
    "    push esi\n"
    "    push eax\n"
    "    call [__imp_WriteFile]\n"
    "    pop ecx\n"
    "    test eax, eax\n"
    "    jz .eio\n"
    "    mov eax, ecx\n"
    "    jmp .out\n"
    ".open:\n"
    "    mov ebx, esi\n"
    "    mov ecx, 0x80000000\n"
    "    mov eax, ebx\n"
    "    and eax, 3\n"
    "    cmp eax, 1\n"
    "    jne .o1\n"
    "    mov ecx, 0x40000000\n"
    ".o1:\n"
    "    cmp eax, 2\n"
    "    jne .o2\n"
    "    mov ecx, 0xC0000000\n"
    ".o2:\n"
    "    mov eax, 3\n"
    "    test ebx, 0x40\n"
    "    jz .o4\n"
    "    mov eax, 4\n"
    "    test ebx, 0x80\n"
    "    jz .o3\n"
    "    mov eax, 1\n"
    "    jmp .o5\n"
    ".o3:\n"
    "    test ebx, 0x200\n"
    "    jz .o5\n"
    "    mov eax, 2\n"
    "    jmp .o5\n"
    ".o4:\n"
    "    test ebx, 0x200\n"
    "    jz .o5\n"
    "    mov eax, 5\n"
    ".o5:\n"
    "    push 0\n"
    "    push 0x80\n"
    "    push eax\n"
    "    push 0\n"
    "    push 3\n"
    "    push ecx\n"
    "    push edi\n"
    "    call [__imp_CreateFileA]\n"
    "    cmp eax, -1\n"
    "    je .enoent\n"
    "    test ebx, 0x400\n"
    "    jz .out\n"
    "    mov ebx, eax\n"
    "    push 2\n"
    "    push 0\n"
    "    push 0\n"
    "    push ebx\n"
    "    call [__imp_SetFilePointer]\n"
    "    mov eax, ebx\n"
    "    jmp .out\n"
    ".close:\n"
    "    push edi\n"
    "    call [__imp_CloseHandle]\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".lseek:\n"
    "    push edx\n"
    "    push 0\n"
    "    push esi\n"
    "    push edi\n"
    "    call [__imp_SetFilePointer]\n"
    "    jmp .out\n"
    ".mmap:\n"
    "    push 4\n"
    "    push 0x3000\n"
    "    push esi\n"
    "    push 0\n"
    "    call [__imp_VirtualAlloc]\n"
    "    test eax, eax\n"
    "    jnz .out\n"
    "    mov eax, -12\n"
    "    jmp .out\n"
    ".munmap:\n"
    "    push 0x8000\n"
    "    push 0\n"
    "    push edi\n"
    "    call [__imp_VirtualFree]\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".brk:\n"
    "    mov ebx, [__cly_brk]\n"
    "    test ebx, ebx\n"
    "    jnz .b1\n"
    "    push 4\n"
    "    push 0x2000\n"
    "    push 0x10000000\n"
    "    push 0\n"
    "    call [__imp_VirtualAlloc]\n"
    "    test eax, eax\n"
    "    jz .zero\n"
    "    mov [__cly_brkbase], eax\n"
    "    mov [__cly_brk], eax\n"
    "    mov [__cly_brkcom], eax\n"
    ".b1:\n"
    "    test edi, edi\n"
    "    jz .b2\n"
    "    mov eax, [__cly_brkbase]\n"
    "    cmp edi, eax\n"
    "    jb .b2\n"
    "    add eax, 0x10000000\n"
    "    cmp edi, eax\n"
    "    ja .b2\n"
    "    mov eax, [__cly_brkcom]\n"
    "    cmp edi, eax\n"
    "    jbe .b3\n"
    "    mov ecx, edi\n"
    "    add ecx, 4095\n"
    "    and ecx, -4096\n"
    "    mov ebx, ecx\n"
    "    sub ecx, eax\n"
    "    push 4\n"
    "    push 0x1000\n"
    "    push ecx\n"
    "    push eax\n"
    "    call [__imp_VirtualAlloc]\n"
    "    test eax, eax\n"
    "    jz .b2\n"
    "    mov [__cly_brkcom], ebx\n"
    ".b3:\n"
    "    mov [__cly_brk], edi\n"
    ".b2:\n"
    "    mov eax, [__cly_brk]\n"
    "    jmp .out\n"
    ".yield:\n"
    "    push 0\n"
    "    call [__imp_Sleep]\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".nanosleep:\n"
    "    mov eax, [edi]\n"
    "    imul eax, eax, 1000\n"
    "    mov ebx, eax\n"
    "    mov eax, [edi+8]\n"
    "    xor edx, edx\n"
    "    mov ecx, 1000000\n"
    "    div ecx\n"
    "    add eax, ebx\n"
    "    push eax\n"
    "    call [__imp_Sleep]\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".getpid:\n"
    "    call [__imp_GetCurrentProcessId]\n"
    "    jmp .out\n"
    ".exit:\n"
    "    push edi\n"
    "    call [__imp_ExitProcess]\n"
    "    jmp .out\n"
    ".getcwd:\n"
    "    push edi\n"
    "    push esi\n"
    "    call [__imp_GetCurrentDirectoryA]\n"
    "    test eax, eax\n"
    "    jz .enoent\n"
    "    inc eax\n"
    "    jmp .out\n"
    ".chdir:\n"
    "    push edi\n"
    "    call [__imp_SetCurrentDirectoryA]\n"
    "    test eax, eax\n"
    "    jz .enoent\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".mkdir:\n"
    "    push 0\n"
    "    push edi\n"
    "    call [__imp_CreateDirectoryA]\n"
    "    test eax, eax\n"
    "    jz .enoent\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".rmdir:\n"
    "    push edi\n"
    "    call [__imp_RemoveDirectoryA]\n"
    "    test eax, eax\n"
    "    jz .enoent\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".unlink:\n"
    "    push edi\n"
    "    call [__imp_DeleteFileA]\n"
    "    test eax, eax\n"
    "    jz .enoent\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".gtod:\n"
    "    call __cly_ft\n"
    "    mov [edi], eax\n"
    "    mov dword [edi+4], 0\n"
    "    mov eax, edx\n"
    "    xor edx, edx\n"
    "    mov ecx, 10\n"
    "    div ecx\n"
    "    mov [edi+8], eax\n"
    "    mov dword [edi+12], 0\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".time:\n"
    "    call __cly_ft\n"
    "    test edi, edi\n"
    "    jz .out\n"
    "    mov [edi], eax\n"
    "    mov dword [edi+4], 0\n"
    "    jmp .out\n"
    ".cgt:\n"
    "    call __cly_ft\n"
    "    mov [esi], eax\n"
    "    mov dword [esi+4], 0\n"
    "    imul edx, edx, 100\n"
    "    mov [esi+8], edx\n"
    "    mov dword [esi+12], 0\n"
    "    xor eax, eax\n"
    ".out:\n"
    "    pop ebp\n"
    "    pop edi\n"
    "    pop esi\n"
    "    pop edx\n"
    "    pop ecx\n"
    "    pop ebx\n"
    "    ret\n"
;
const char rt_src_mac[] =
    "bits 32\n"
    "section .data\n"
    "__cly_brk dd 0\n"
    "__cly_brkbase dd 0\n"
    "section .text\n"
    "__cly_syscall:\n"
    "    push ebx\n"
    "    push ecx\n"
    "    push edx\n"
    "    push esi\n"
    "    push edi\n"
    "    push ebp\n"
    "    cmp eax, 2\n"
    "    je .open\n"
    "    cmp eax, 8\n"
    "    je .lseek\n"
    "    cmp eax, 9\n"
    "    je .mmap\n"
    "    cmp eax, 12\n"
    "    je .brk\n"
    "    cmp eax, 35\n"
    "    je .nanosleep\n"
    "    cmp eax, 96\n"
    "    je .gtod\n"
    "    cmp eax, 201\n"
    "    je .time\n"
    "    cmp eax, 228\n"
    "    je .cgt\n"
    "    cmp eax, __cly_nsys\n"
    "    jae .bad\n"
    "    movzx eax, word [__cly_sysmap+eax*2]\n"
    "    cmp eax, 0xFFFF\n"
    "    je .bad\n"
    "    push dword [__cly_vregs+4]\n"
    "    push dword [__cly_vregs]\n"
    "    push dword [__cly_vregs+8]\n"
    "    push edx\n"
    "    push esi\n"
    "    push edi\n"
    "    call .do\n"
    "    add esp, 24\n"
    "    jmp .out\n"
    ".do:\n"
    "    int 0x80\n"
    "    jnc .done\n"
    "    neg eax\n"
    ".done:\n"
    "    ret\n"
    ".bad:\n"
    "    mov eax, -38\n"
    "    jmp .out\n"
    ".open:\n"
    "    mov ecx, esi\n"
    "    and ecx, 3\n"
    "    test esi, 0x40\n"
    "    jz .o1\n"
    "    or ecx, 0x200\n"
    ".o1:\n"
    "    test esi, 0x200\n"
    "    jz .o2\n"
    "    or ecx, 0x400\n"
    ".o2:\n"
    "    test esi, 0x400\n"
    "    jz .o3\n"
    "    or ecx, 8\n"
    ".o3:\n"
    "    test esi, 0x80\n"
    "    jz .o4\n"
    "    or ecx, 0x800\n"
    ".o4:\n"
    "    test esi, 0x800\n"
    "    jz .o5\n"
    "    or ecx, 4\n"
    ".o5:\n"
    "    push edx\n"
    "    push ecx\n"
    "    push edi\n"
    "    mov eax, 5\n"
    "    call .do\n"
    "    add esp, 12\n"
    "    jmp .out\n"
    ".lseek:\n"
    "    mov ecx, esi\n"
    "    sar ecx, 31\n"
    "    push edx\n"
    "    push ecx\n"
    "    push esi\n"
    "    push edi\n"
    "    mov eax, 199\n"
    "    call .do\n"
    "    add esp, 16\n"
    "    jmp .out\n"
    ".mmap:\n"
    "    mov ecx, [__cly_vregs+8]\n"
    "    test ecx, 0x20\n"
    "    jz .m1\n"
    "    and ecx, -33\n"
    "    or ecx, 0x1000\n"
    ".m1:\n"
    "    push 0\n"
    "    push dword [__cly_vregs+4]\n"
    "    push dword [__cly_vregs]\n"
    "    push ecx\n"
    "    push edx\n"
    "    push esi\n"
    "    push edi\n"
    "    mov eax, 197\n"
    "    call .do\n"
    "    add esp, 28\n"
    "    jmp .out\n"
    ".brk:\n"
    "    mov eax, [__cly_brkbase]\n"
    "    test eax, eax\n"
    "    jnz .br1\n"
    "    push 0\n"
    "    push 0\n"
    "    push -1\n"
    "    push 0x1002\n"
    "    push 3\n"
    "    push 0x10000000\n"
    "    push 0\n"
    "    mov eax, 197\n"
    "    call .do\n"
    "    add esp, 28\n"
    "    cmp eax, -4096\n"
    "    ja .brbad\n"
    "    mov [__cly_brkbase], eax\n"
    "    mov [__cly_brk], eax\n"
    ".br1:\n"
    "    test edi, edi\n"
    "    jz .br2\n"
    "    mov ecx, [__cly_brkbase]\n"
    "    cmp edi, ecx\n"
    "    jb .br2\n"
    "    add ecx, 0x10000000\n"
    "    cmp edi, ecx\n"
    "    ja .br2\n"
    "    mov [__cly_brk], edi\n"
    ".br2:\n"
    "    mov eax, [__cly_brk]\n"
    "    jmp .out\n"
    ".brbad:\n"
    "    mov eax, -12\n"
    "    jmp .out\n"
    ".nanosleep:\n"
    "    mov eax, [edi+8]\n"
    "    xor edx, edx\n"
    "    mov ecx, 1000\n"
    "    div ecx\n"
    "    push eax\n"
    "    push dword [edi]\n"
    "    mov eax, esp\n"
    "    push eax\n"
    "    push 0\n"
    "    push 0\n"
    "    push 0\n"
    "    push 0\n"
    "    mov eax, 93\n"
    "    call .do\n"
    "    add esp, 28\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".gtod:\n"
    "    sub esp, 8\n"
    "    push 0\n"
    "    lea eax, [esp+4]\n"
    "    push eax\n"
    "    mov eax, 116\n"
    "    call .do\n"
    "    add esp, 8\n"
    "    pop eax\n"
    "    pop ecx\n"
    "    test edi, edi\n"
    "    jz .gd1\n"
    "    mov [edi], eax\n"
    "    mov dword [edi+4], 0\n"
    "    mov [edi+8], ecx\n"
    "    mov dword [edi+12], 0\n"
    ".gd1:\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".time:\n"
    "    sub esp, 8\n"
    "    push 0\n"
    "    lea eax, [esp+4]\n"
    "    push eax\n"
    "    mov eax, 116\n"
    "    call .do\n"
    "    add esp, 8\n"
    "    pop eax\n"
    "    pop ecx\n"
    "    test edi, edi\n"
    "    jz .out\n"
    "    mov [edi], eax\n"
    "    mov dword [edi+4], 0\n"
    "    jmp .out\n"
    ".cgt:\n"
    "    sub esp, 8\n"
    "    push 0\n"
    "    lea eax, [esp+4]\n"
    "    push eax\n"
    "    mov eax, 116\n"
    "    call .do\n"
    "    add esp, 8\n"
    "    pop eax\n"
    "    pop ecx\n"
    "    imul ecx, ecx, 1000\n"
    "    mov [esi], eax\n"
    "    mov dword [esi+4], 0\n"
    "    mov [esi+8], ecx\n"
    "    mov dword [esi+12], 0\n"
    "    xor eax, eax\n"
    ".out:\n"
    "    pop ebp\n"
    "    pop edi\n"
    "    pop esi\n"
    "    pop edx\n"
    "    pop ecx\n"
    "    pop ebx\n"
    "    ret\n"
;
const char rt_src_bare[] =
    "bits 32\n"
    "extern __cly_image_end\n"
    "section .data\n"
    "__cly_cur dd 0\n"
    "__cly_shift dd 0\n"
    "__cly_ready dd 0\n"
    "__cly_heap dd 0\n"
    "__cly_brk dd 0\n"
    "__cly_brkbase dd 0\n"
    "section .text\n"
    "__cly_init:\n"
    "    pushad\n"
    "    mov dword [__cly_ready], 1\n"
    "    mov dx, 0x3F9\n"
    "    xor al, al\n"
    "    out dx, al\n"
    "    mov dx, 0x3FB\n"
    "    mov al, 0x80\n"
    "    out dx, al\n"
    "    mov dx, 0x3F8\n"
    "    mov al, 1\n"
    "    out dx, al\n"
    "    mov dx, 0x3F9\n"
    "    xor al, al\n"
    "    out dx, al\n"
    "    mov dx, 0x3FB\n"
    "    mov al, 3\n"
    "    out dx, al\n"
    "    mov dx, 0x3FA\n"
    "    mov al, 0xC7\n"
    "    out dx, al\n"
    "    mov dx, 0x3FC\n"
    "    mov al, 0x0B\n"
    "    out dx, al\n"
    "    mov edi, 0xB8000\n"
    "    mov ecx, 1000\n"
    "    mov eax, 0x07200720\n"
    "    cld\n"
    "    rep stosd\n"
    "    mov dword [__cly_cur], 0\n"
    "    popad\n"
    "    ret\n"
    "__cly_putc:\n"
    "    pushad\n"
    "    movzx ebx, al\n"
    "    out 0xE9, al\n"
    "    mov dx, 0x3FD\n"
    "    mov ecx, 65536\n"
    ".w:\n"
    "    in al, dx\n"
    "    cmp al, 0xFF\n"
    "    je .vga\n"
    "    test al, 0x20\n"
    "    jnz .snd\n"
    "    dec ecx\n"
    "    jnz .w\n"
    "    jmp .vga\n"
    ".snd:\n"
    "    mov dx, 0x3F8\n"
    "    mov al, bl\n"
    "    out dx, al\n"
    ".vga:\n"
    "    mov edi, [__cly_cur]\n"
    "    cmp bl, 10\n"
    "    je .nl\n"
    "    cmp bl, 13\n"
    "    je .cr\n"
    "    cmp bl, 8\n"
    "    je .bs\n"
    "    cmp bl, 9\n"
    "    je .tab\n"
    "    mov al, bl\n"
    "    mov ah, 7\n"
    "    mov [0xB8000+edi*2], ax\n"
    "    inc edi\n"
    "    jmp .chk\n"
    ".nl:\n"
    "    mov eax, edi\n"
    "    xor edx, edx\n"
    "    mov ecx, 80\n"
    "    div ecx\n"
    "    sub edi, edx\n"
    "    add edi, 80\n"
    "    jmp .chk\n"
    ".cr:\n"
    "    mov eax, edi\n"
    "    xor edx, edx\n"
    "    mov ecx, 80\n"
    "    div ecx\n"
    "    sub edi, edx\n"
    "    jmp .chk\n"
    ".bs:\n"
    "    test edi, edi\n"
    "    jz .chk\n"
    "    dec edi\n"
    "    mov word [0xB8000+edi*2], 0x0720\n"
    "    jmp .chk\n"
    ".tab:\n"
    "    add edi, 8\n"
    "    and edi, -8\n"
    ".chk:\n"
    "    cmp edi, 2000\n"
    "    jb .done\n"
    "    mov esi, 0xB80A0\n"
    "    mov edi, 0xB8000\n"
    "    mov ecx, 960\n"
    "    cld\n"
    "    rep movsd\n"
    "    mov ecx, 40\n"
    "    mov eax, 0x07200720\n"
    "    rep stosd\n"
    "    mov edi, 1920\n"
    ".done:\n"
    "    mov [__cly_cur], edi\n"
    "    mov dx, 0x3D4\n"
    "    mov al, 0x0F\n"
    "    out dx, al\n"
    "    inc dx\n"
    "    mov eax, edi\n"
    "    out dx, al\n"
    "    dec dx\n"
    "    mov al, 0x0E\n"
    "    out dx, al\n"
    "    inc dx\n"
    "    mov eax, edi\n"
    "    shr eax, 8\n"
    "    out dx, al\n"
    "    popad\n"
    "    ret\n"
    "__cly_getc:\n"
    "    push ebx\n"
    "    push ecx\n"
    "    push edx\n"
    ".poll:\n"
    "    mov dx, 0x3FD\n"
    "    in al, dx\n"
    "    cmp al, 0xFF\n"
    "    je .kbd\n"
    "    test al, 1\n"
    "    jz .kbd\n"
    "    mov dx, 0x3F8\n"
    "    in al, dx\n"
    "    movzx eax, al\n"
    "    cmp al, 13\n"
    "    jne .fin\n"
    "    mov al, 10\n"
    "    jmp .fin\n"
    ".kbd:\n"
    "    in al, 0x64\n"
    "    test al, 1\n"
    "    jz .poll\n"
    "    in al, 0x60\n"
    "    movzx ecx, al\n"
    "    cmp cl, 0x2A\n"
    "    je .shon\n"
    "    cmp cl, 0x36\n"
    "    je .shon\n"
    "    cmp cl, 0xAA\n"
    "    je .shoff\n"
    "    cmp cl, 0xB6\n"
    "    je .shoff\n"
    "    test cl, 0x80\n"
    "    jnz .poll\n"
    "    cmp cl, 0x39\n"
    "    ja .poll\n"
    "    cmp dword [__cly_shift], 0\n"
    "    je .norm\n"
    "    movzx eax, byte [__cly_ktab_s+ecx]\n"
    "    jmp .have\n"
    ".norm:\n"
    "    movzx eax, byte [__cly_ktab+ecx]\n"
    ".have:\n"
    "    test eax, eax\n"
    "    jz .poll\n"
    "    jmp .fin\n"
    ".shon:\n"
    "    mov dword [__cly_shift], 1\n"
    "    jmp .poll\n"
    ".shoff:\n"
    "    mov dword [__cly_shift], 0\n"
    "    jmp .poll\n"
    ".fin:\n"
    "    pop edx\n"
    "    pop ecx\n"
    "    pop ebx\n"
    "    ret\n"
    "__cly_heapptr:\n"
    "    mov eax, [__cly_heap]\n"
    "    test eax, eax\n"
    "    jnz .r\n"
    "    mov eax, __cly_image_end\n"
    "    add eax, 4095\n"
    "    and eax, -4096\n"
    "    cmp eax, 0x100000\n"
    "    jae .r\n"
    "    mov eax, 0x100000\n"
    ".r:\n"
    "    ret\n"
    "__cly_alloc:\n"
    "    call __cly_heapptr\n"
    "    mov ebx, eax\n"
    "    mov edi, eax\n"
    "    mov ecx, edx\n"
    "    xor eax, eax\n"
    "    cld\n"
    "    rep stosb\n"
    "    lea eax, [ebx+edx]\n"
    "    mov [__cly_heap], eax\n"
    "    mov eax, ebx\n"
    "    ret\n"
    "__cly_syscall:\n"
    "    push ebx\n"
    "    push ecx\n"
    "    push edx\n"
    "    push esi\n"
    "    push edi\n"
    "    push ebp\n"
    "    cmp dword [__cly_ready], 0\n"
    "    jne .go\n"
    "    push eax\n"
    "    call __cly_init\n"
    "    pop eax\n"
    ".go:\n"
    "    cmp eax, 1\n"
    "    je .write\n"
    "    cmp eax, 0\n"
    "    je .read\n"
    "    cmp eax, 9\n"
    "    je .mmap\n"
    "    cmp eax, 12\n"
    "    je .brk\n"
    "    cmp eax, 11\n"
    "    je .zero\n"
    "    cmp eax, 3\n"
    "    je .zero\n"
    "    cmp eax, 24\n"
    "    je .zero\n"
    "    cmp eax, 39\n"
    "    je .getpid\n"
    "    cmp eax, 35\n"
    "    je .sleep\n"
    "    cmp eax, 60\n"
    "    je .exit\n"
    "    cmp eax, 231\n"
    "    je .exit\n"
    "    cmp eax, 16\n"
    "    je .notty\n"
    "    mov eax, -38\n"
    "    jmp .out\n"
    ".zero:\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".getpid:\n"
    "    mov eax, 1\n"
    "    jmp .out\n"
    ".notty:\n"
    "    mov eax, -25\n"
    "    jmp .out\n"
    ".ebadf:\n"
    "    mov eax, -9\n"
    "    jmp .out\n"
    ".write:\n"
    "    cmp edi, 1\n"
    "    jb .ebadf\n"
    "    cmp edi, 2\n"
    "    ja .ebadf\n"
    "    mov ecx, edx\n"
    "    mov ebx, edx\n"
    "    test ecx, ecx\n"
    "    jz .wdone\n"
    ".wl:\n"
    "    mov al, [esi]\n"
    "    call __cly_putc\n"
    "    inc esi\n"
    "    dec ecx\n"
    "    jnz .wl\n"
    ".wdone:\n"
    "    mov eax, ebx\n"
    "    jmp .out\n"
    ".read:\n"
    "    test edi, edi\n"
    "    jnz .ebadf\n"
    "    xor ebx, ebx\n"
    "    test edx, edx\n"
    "    jz .rdone\n"
    ".rl:\n"
    "    call __cly_getc\n"
    "    cmp al, 8\n"
    "    je .rbs\n"
    "    cmp al, 127\n"
    "    je .rbs\n"
    "    mov [esi+ebx], al\n"
    "    inc ebx\n"
    "    call __cly_putc\n"
    "    cmp al, 10\n"
    "    je .rdone\n"
    "    cmp ebx, edx\n"
    "    jb .rl\n"
    "    jmp .rdone\n"
    ".rbs:\n"
    "    test ebx, ebx\n"
    "    jz .rl\n"
    "    dec ebx\n"
    "    mov al, 8\n"
    "    call __cly_putc\n"
    "    mov al, 32\n"
    "    call __cly_putc\n"
    "    mov al, 8\n"
    "    call __cly_putc\n"
    "    jmp .rl\n"
    ".rdone:\n"
    "    mov eax, ebx\n"
    "    jmp .out\n"
    ".mmap:\n"
    "    mov edx, esi\n"
    "    add edx, 4095\n"
    "    and edx, -4096\n"
    "    call __cly_alloc\n"
    "    jmp .out\n"
    ".brk:\n"
    "    cmp dword [__cly_brkbase], 0\n"
    "    jne .b1\n"
    "    mov edx, 0x1000000\n"
    "    call __cly_alloc\n"
    "    mov [__cly_brkbase], eax\n"
    "    mov [__cly_brk], eax\n"
    ".b1:\n"
    "    test edi, edi\n"
    "    jz .b2\n"
    "    cmp edi, [__cly_brkbase]\n"
    "    jb .b2\n"
    "    mov eax, [__cly_brkbase]\n"
    "    add eax, 0x1000000\n"
    "    cmp edi, eax\n"
    "    ja .b2\n"
    "    mov [__cly_brk], edi\n"
    ".b2:\n"
    "    mov eax, [__cly_brk]\n"
    "    jmp .out\n"
    ".sleep:\n"
    "    mov eax, [edi+8]\n"
    "    xor edx, edx\n"
    "    mov ecx, 1000000\n"
    "    div ecx\n"
    "    mov ebx, eax\n"
    "    mov eax, [edi]\n"
    "    imul eax, eax, 1000\n"
    "    add ebx, eax\n"
    "    imul ebx, ebx, 1000\n"
    ".s1:\n"
    "    test ebx, ebx\n"
    "    jz .zero\n"
    "    out 0x80, al\n"
    "    dec ebx\n"
    "    jmp .s1\n"
    ".exit:\n"
    "    mov eax, edi\n"
    "    out 0xF4, al\n"
    "    mov dx, 0x604\n"
    "    mov ax, 0x2000\n"
    "    out dx, ax\n"
    "    mov dx, 0xB004\n"
    "    out dx, ax\n"
    "    mov dx, 0x4004\n"
    "    mov ax, 0x3400\n"
    "    out dx, ax\n"
    "    cli\n"
    ".h:\n"
    "    hlt\n"
    "    jmp .h\n"
    ".out:\n"
    "    pop ebp\n"
    "    pop edi\n"
    "    pop esi\n"
    "    pop edx\n"
    "    pop ecx\n"
    "    pop ebx\n"
    "    ret\n"
;
const char rt_src_win64[] =
    "bits 64\n"
    "default rel\n"
    "import __imp_GetStdHandle kernel32.dll GetStdHandle\n"
    "import __imp_WriteFile kernel32.dll WriteFile\n"
    "import __imp_ReadFile kernel32.dll ReadFile\n"
    "import __imp_CreateFileA kernel32.dll CreateFileA\n"
    "import __imp_CloseHandle kernel32.dll CloseHandle\n"
    "import __imp_SetFilePointer kernel32.dll SetFilePointer\n"
    "import __imp_VirtualAlloc kernel32.dll VirtualAlloc\n"
    "import __imp_VirtualFree kernel32.dll VirtualFree\n"
    "import __imp_ExitProcess kernel32.dll ExitProcess\n"
    "import __imp_GetCurrentProcessId kernel32.dll GetCurrentProcessId\n"
    "import __imp_Sleep kernel32.dll Sleep\n"
    "import __imp_GetSystemTimeAsFileTime kernel32.dll GetSystemTimeAsFileTime\n"
    "import __imp_DeleteFileA kernel32.dll DeleteFileA\n"
    "import __imp_CreateDirectoryA kernel32.dll CreateDirectoryA\n"
    "import __imp_RemoveDirectoryA kernel32.dll RemoveDirectoryA\n"
    "import __imp_GetCurrentDirectoryA kernel32.dll GetCurrentDirectoryA\n"
    "import __imp_SetCurrentDirectoryA kernel32.dll SetCurrentDirectoryA\n"
    "section .data\n"
    "align 8\n"
    "__cly_brk dq 0\n"
    "__cly_brkbase dq 0\n"
    "__cly_brkcom dq 0\n"
    "section .text\n"
    "__cly_h:\n"
    "    cmp edi, 2\n"
    "    ja .raw\n"
    "    mov ecx, -10\n"
    "    sub ecx, edi\n"
    "    sub rsp, 40\n"
    "    call [__imp_GetStdHandle]\n"
    "    add rsp, 40\n"
    "    ret\n"
    ".raw:\n"
    "    mov rax, rdi\n"
    "    ret\n"
    "__cly_ft:\n"
    "    sub rsp, 56\n"
    "    lea rcx, [rsp+32]\n"
    "    call [__imp_GetSystemTimeAsFileTime]\n"
    "    mov rax, [rsp+32]\n"
    "    add rsp, 56\n"
    "    mov rcx, 116444736000000000\n"
    "    sub rax, rcx\n"
    "    xor edx, edx\n"
    "    mov rcx, 10000000\n"
    "    div rcx\n"
    "    ret\n"
    "__cly_syscall:\n"
    "    push rbx\n"
    "    push rbp\n"
    "    push rdx\n"
    "    push rsi\n"
    "    push rdi\n"
    "    push r8\n"
    "    push r9\n"
    "    push r10\n"
    "    mov rbp, rsp\n"
    "    and rsp, -16\n"
    "    sub rsp, 96\n"
    "    cmp eax, 0\n"
    "    je .read\n"
    "    cmp eax, 1\n"
    "    je .write\n"
    "    cmp eax, 2\n"
    "    je .open\n"
    "    cmp eax, 3\n"
    "    je .close\n"
    "    cmp eax, 8\n"
    "    je .lseek\n"
    "    cmp eax, 9\n"
    "    je .mmap\n"
    "    cmp eax, 11\n"
    "    je .munmap\n"
    "    cmp eax, 12\n"
    "    je .brk\n"
    "    cmp eax, 16\n"
    "    je .notty\n"
    "    cmp eax, 24\n"
    "    je .yield\n"
    "    cmp eax, 35\n"
    "    je .nanosleep\n"
    "    cmp eax, 39\n"
    "    je .getpid\n"
    "    cmp eax, 60\n"
    "    je .exit\n"
    "    cmp eax, 79\n"
    "    je .getcwd\n"
    "    cmp eax, 80\n"
    "    je .chdir\n"
    "    cmp eax, 83\n"
    "    je .mkdir\n"
    "    cmp eax, 84\n"
    "    je .rmdir\n"
    "    cmp eax, 87\n"
    "    je .unlink\n"
    "    cmp eax, 96\n"
    "    je .gtod\n"
    "    cmp eax, 102\n"
    "    je .zero\n"
    "    cmp eax, 104\n"
    "    je .zero\n"
    "    cmp eax, 107\n"
    "    je .zero\n"
    "    cmp eax, 108\n"
    "    je .zero\n"
    "    cmp eax, 201\n"
    "    je .time\n"
    "    cmp eax, 228\n"
    "    je .cgt\n"
    "    cmp eax, 231\n"
    "    je .exit\n"
    "    mov rax, -38\n"
    "    jmp .out\n"
    ".zero:\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".notty:\n"
    "    mov rax, -25\n"
    "    jmp .out\n"
    ".eio:\n"
    "    mov rax, -5\n"
    "    jmp .out\n"
    ".enoent:\n"
    "    mov rax, -2\n"
    "    jmp .out\n"
    ".read:\n"
    "    mov rbx, rdx\n"
    "    call __cly_h\n"
    "    mov rcx, rax\n"
    "    mov rdx, rsi\n"
    "    mov r8, rbx\n"
    "    lea r9, [rsp+64]\n"
    "    mov qword [rsp+32], 0\n"
    "    call [__imp_ReadFile]\n"
    "    test eax, eax\n"
    "    jz .eio\n"
    "    mov eax, [rsp+64]\n"
    "    jmp .out\n"
    ".write:\n"
    "    mov rbx, rdx\n"
    "    call __cly_h\n"
    "    mov rcx, rax\n"
    "    mov rdx, rsi\n"
    "    mov r8, rbx\n"
    "    lea r9, [rsp+64]\n"
    "    mov qword [rsp+32], 0\n"
    "    call [__imp_WriteFile]\n"
    "    test eax, eax\n"
    "    jz .eio\n"
    "    mov eax, [rsp+64]\n"
    "    jmp .out\n"
    ".open:\n"
    "    mov rbx, rsi\n"
    "    mov edx, 0x80000000\n"
    "    mov eax, ebx\n"
    "    and eax, 3\n"
    "    cmp eax, 1\n"
    "    jne .o1\n"
    "    mov edx, 0x40000000\n"
    ".o1:\n"
    "    cmp eax, 2\n"
    "    jne .o2\n"
    "    mov edx, 0xC0000000\n"
    ".o2:\n"
    "    mov eax, 3\n"
    "    test ebx, 0x40\n"
    "    jz .o4\n"
    "    mov eax, 4\n"
    "    test ebx, 0x80\n"
    "    jz .o3\n"
    "    mov eax, 1\n"
    "    jmp .o5\n"
    ".o3:\n"
    "    test ebx, 0x200\n"
    "    jz .o5\n"
    "    mov eax, 2\n"
    "    jmp .o5\n"
    ".o4:\n"
    "    test ebx, 0x200\n"
    "    jz .o5\n"
    "    mov eax, 5\n"
    ".o5:\n"
    "    mov rcx, rdi\n"
    "    mov r8d, 3\n"
    "    xor r9d, r9d\n"
    "    mov [rsp+32], rax\n"
    "    mov qword [rsp+40], 0x80\n"
    "    mov qword [rsp+48], 0\n"
    "    call [__imp_CreateFileA]\n"
    "    cmp rax, -1\n"
    "    je .enoent\n"
    "    test ebx, 0x400\n"
    "    jz .out\n"
    "    mov rbx, rax\n"
    "    mov rcx, rbx\n"
    "    xor edx, edx\n"
    "    xor r8d, r8d\n"
    "    mov r9d, 2\n"
    "    call [__imp_SetFilePointer]\n"
    "    mov rax, rbx\n"
    "    jmp .out\n"
    ".close:\n"
    "    mov rcx, rdi\n"
    "    call [__imp_CloseHandle]\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".lseek:\n"
    "    mov r9d, edx\n"
    "    mov rcx, rdi\n"
    "    mov rdx, rsi\n"
    "    xor r8d, r8d\n"
    "    call [__imp_SetFilePointer]\n"
    "    mov eax, eax\n"
    "    jmp .out\n"
    ".mmap:\n"
    "    xor ecx, ecx\n"
    "    mov rdx, rsi\n"
    "    mov r8d, 0x3000\n"
    "    mov r9d, 4\n"
    "    call [__imp_VirtualAlloc]\n"
    "    test rax, rax\n"
    "    jnz .out\n"
    "    mov rax, -12\n"
    "    jmp .out\n"
    ".munmap:\n"
    "    mov rcx, rdi\n"
    "    xor edx, edx\n"
    "    mov r8d, 0x8000\n"
    "    call [__imp_VirtualFree]\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".brk:\n"
    "    mov rbx, [__cly_brk]\n"
    "    test rbx, rbx\n"
    "    jnz .b1\n"
    "    xor ecx, ecx\n"
    "    mov edx, 0x10000000\n"
    "    mov r8d, 0x2000\n"
    "    mov r9d, 4\n"
    "    call [__imp_VirtualAlloc]\n"
    "    test rax, rax\n"
    "    jz .zero\n"
    "    mov [__cly_brkbase], rax\n"
    "    mov [__cly_brk], rax\n"
    "    mov [__cly_brkcom], rax\n"
    ".b1:\n"
    "    test rdi, rdi\n"
    "    jz .b2\n"
    "    mov rax, [__cly_brkbase]\n"
    "    cmp rdi, rax\n"
    "    jb .b2\n"
    "    add rax, 0x10000000\n"
    "    cmp rdi, rax\n"
    "    ja .b2\n"
    "    mov rax, [__cly_brkcom]\n"
    "    cmp rdi, rax\n"
    "    jbe .b3\n"
    "    mov rdx, rdi\n"
    "    add rdx, 4095\n"
    "    and rdx, -4096\n"
    "    mov rbx, rdx\n"
    "    sub rdx, rax\n"
    "    mov rcx, rax\n"
    "    mov r8d, 0x1000\n"
    "    mov r9d, 4\n"
    "    call [__imp_VirtualAlloc]\n"
    "    test rax, rax\n"
    "    jz .b2\n"
    "    mov [__cly_brkcom], rbx\n"
    ".b3:\n"
    "    mov [__cly_brk], rdi\n"
    ".b2:\n"
    "    mov rax, [__cly_brk]\n"
    "    jmp .out\n"
    ".yield:\n"
    "    xor ecx, ecx\n"
    "    call [__imp_Sleep]\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".nanosleep:\n"
    "    mov rax, [rdi]\n"
    "    imul rax, rax, 1000\n"
    "    mov rbx, rax\n"
    "    mov rax, [rdi+8]\n"
    "    xor edx, edx\n"
    "    mov ecx, 1000000\n"
    "    div rcx\n"
    "    add rax, rbx\n"
    "    mov ecx, eax\n"
    "    call [__imp_Sleep]\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".getpid:\n"
    "    call [__imp_GetCurrentProcessId]\n"
    "    jmp .out\n"
    ".exit:\n"
    "    mov ecx, edi\n"
    "    call [__imp_ExitProcess]\n"
    "    jmp .out\n"
    ".getcwd:\n"
    "    mov rcx, rsi\n"
    "    mov rdx, rdi\n"
    "    call [__imp_GetCurrentDirectoryA]\n"
    "    test eax, eax\n"
    "    jz .enoent\n"
    "    inc eax\n"
    "    jmp .out\n"
    ".chdir:\n"
    "    mov rcx, rdi\n"
    "    call [__imp_SetCurrentDirectoryA]\n"
    "    test eax, eax\n"
    "    jz .enoent\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".mkdir:\n"
    "    mov rcx, rdi\n"
    "    xor edx, edx\n"
    "    call [__imp_CreateDirectoryA]\n"
    "    test eax, eax\n"
    "    jz .enoent\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".rmdir:\n"
    "    mov rcx, rdi\n"
    "    call [__imp_RemoveDirectoryA]\n"
    "    test eax, eax\n"
    "    jz .enoent\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".unlink:\n"
    "    mov rcx, rdi\n"
    "    call [__imp_DeleteFileA]\n"
    "    test eax, eax\n"
    "    jz .enoent\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".gtod:\n"
    "    call __cly_ft\n"
    "    mov [rdi], rax\n"
    "    mov rax, rdx\n"
    "    xor edx, edx\n"
    "    mov ecx, 10\n"
    "    div rcx\n"
    "    mov [rdi+8], rax\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".time:\n"
    "    call __cly_ft\n"
    "    test rdi, rdi\n"
    "    jz .out\n"
    "    mov [rdi], rax\n"
    "    jmp .out\n"
    ".cgt:\n"
    "    call __cly_ft\n"
    "    mov [rsi], rax\n"
    "    imul rdx, rdx, 100\n"
    "    mov [rsi+8], rdx\n"
    "    xor eax, eax\n"
    ".out:\n"
    "    mov rsp, rbp\n"
    "    pop r10\n"
    "    pop r9\n"
    "    pop r8\n"
    "    pop rdi\n"
    "    pop rsi\n"
    "    pop rdx\n"
    "    pop rbp\n"
    "    pop rbx\n"
    "    ret\n"
;
const char rt_src_mac64[] =
    "bits 64\n"
    "default rel\n"
    "section .data\n"
    "align 8\n"
    "__cly_brk dq 0\n"
    "__cly_brkbase dq 0\n"
    "section .text\n"
    "__cly_syscall:\n"
    "    push rdx\n"
    "    cmp eax, 2\n"
    "    je .open\n"
    "    cmp eax, 9\n"
    "    je .mmap\n"
    "    cmp eax, 12\n"
    "    je .brk\n"
    "    cmp eax, 35\n"
    "    je .nanosleep\n"
    "    cmp eax, 96\n"
    "    je .gtod\n"
    "    cmp eax, 201\n"
    "    je .time\n"
    "    cmp eax, 228\n"
    "    je .cgt\n"
    "    cmp eax, __cly_nsys\n"
    "    jae .bad\n"
    "    lea rcx, [__cly_sysmap]\n"
    "    movzx eax, word [rcx+rax*2]\n"
    "    cmp eax, 0xFFFF\n"
    "    je .bad\n"
    "    call .do\n"
    "    jmp .out\n"
    ".do:\n"
    "    or eax, 0x2000000\n"
    "    db 0x0f, 0x05\n"
    "    jnc .done\n"
    "    neg rax\n"
    ".done:\n"
    "    ret\n"
    ".bad:\n"
    "    mov rax, -38\n"
    "    jmp .out\n"
    ".open:\n"
    "    mov ecx, esi\n"
    "    and ecx, 3\n"
    "    test esi, 0x40\n"
    "    jz .o1\n"
    "    or ecx, 0x200\n"
    ".o1:\n"
    "    test esi, 0x200\n"
    "    jz .o2\n"
    "    or ecx, 0x400\n"
    ".o2:\n"
    "    test esi, 0x400\n"
    "    jz .o3\n"
    "    or ecx, 8\n"
    ".o3:\n"
    "    test esi, 0x80\n"
    "    jz .o4\n"
    "    or ecx, 0x800\n"
    ".o4:\n"
    "    test esi, 0x800\n"
    "    jz .o5\n"
    "    or ecx, 4\n"
    ".o5:\n"
    "    mov esi, ecx\n"
    "    mov eax, 5\n"
    "    call .do\n"
    "    jmp .out\n"
    ".mmap:\n"
    "    test r10d, 0x20\n"
    "    jz .m1\n"
    "    and r10d, -33\n"
    "    or r10d, 0x1000\n"
    ".m1:\n"
    "    mov eax, 197\n"
    "    call .do\n"
    "    jmp .out\n"
    ".brk:\n"
    "    mov rax, [__cly_brkbase]\n"
    "    test rax, rax\n"
    "    jnz .br1\n"
    "    push rdi\n"
    "    push rsi\n"
    "    push rdx\n"
    "    push r10\n"
    "    push r8\n"
    "    push r9\n"
    "    xor edi, edi\n"
    "    mov esi, 0x10000000\n"
    "    mov edx, 3\n"
    "    mov r10d, 0x1002\n"
    "    mov r8, -1\n"
    "    xor r9d, r9d\n"
    "    mov eax, 197\n"
    "    call .do\n"
    "    pop r9\n"
    "    pop r8\n"
    "    pop r10\n"
    "    pop rdx\n"
    "    pop rsi\n"
    "    pop rdi\n"
    "    cmp rax, -4096\n"
    "    ja .brbad\n"
    "    mov [__cly_brkbase], rax\n"
    "    mov [__cly_brk], rax\n"
    ".br1:\n"
    "    test rdi, rdi\n"
    "    jz .br2\n"
    "    mov rcx, [__cly_brkbase]\n"
    "    cmp rdi, rcx\n"
    "    jb .br2\n"
    "    add rcx, 0x10000000\n"
    "    cmp rdi, rcx\n"
    "    ja .br2\n"
    "    mov [__cly_brk], rdi\n"
    ".br2:\n"
    "    mov rax, [__cly_brk]\n"
    "    jmp .out\n"
    ".brbad:\n"
    "    mov rax, -12\n"
    "    jmp .out\n"
    ".nanosleep:\n"
    "    mov rax, [rdi+8]\n"
    "    xor edx, edx\n"
    "    mov ecx, 1000\n"
    "    div rcx\n"
    "    push rdi\n"
    "    push rsi\n"
    "    push r10\n"
    "    push r8\n"
    "    push rax\n"
    "    push qword [rdi]\n"
    "    mov r8, rsp\n"
    "    xor edi, edi\n"
    "    xor esi, esi\n"
    "    xor edx, edx\n"
    "    xor r10d, r10d\n"
    "    mov eax, 93\n"
    "    call .do\n"
    "    add rsp, 16\n"
    "    pop r8\n"
    "    pop r10\n"
    "    pop rsi\n"
    "    pop rdi\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".tod:\n"
    "    push rdi\n"
    "    push rsi\n"
    "    sub rsp, 16\n"
    "    mov rdi, rsp\n"
    "    xor esi, esi\n"
    "    mov eax, 116\n"
    "    call .do\n"
    "    mov rax, [rsp]\n"
    "    mov ecx, [rsp+8]\n"
    "    add rsp, 16\n"
    "    pop rsi\n"
    "    pop rdi\n"
    "    ret\n"
    ".gtod:\n"
    "    call .tod\n"
    "    test rdi, rdi\n"
    "    jz .gd1\n"
    "    mov [rdi], rax\n"
    "    mov [rdi+8], rcx\n"
    ".gd1:\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".time:\n"
    "    call .tod\n"
    "    test rdi, rdi\n"
    "    jz .out\n"
    "    mov [rdi], rax\n"
    "    jmp .out\n"
    ".cgt:\n"
    "    call .tod\n"
    "    imul rcx, rcx, 1000\n"
    "    mov [rsi], rax\n"
    "    mov [rsi+8], rcx\n"
    "    xor eax, eax\n"
    ".out:\n"
    "    pop rdx\n"
    "    ret\n"
;
const char rt_src_bare64[] =
    "bits 64\n"
    "default rel\n"
    "extern __cly_image_end\n"
    "section .data\n"
    "align 8\n"
    "__cly_cur dq 0\n"
    "__cly_heap dq 0\n"
    "__cly_brk dq 0\n"
    "__cly_brkbase dq 0\n"
    "__cly_shift dd 0\n"
    "__cly_ready dd 0\n"
    "section .text\n"
    "__cly_init:\n"
    "    push rax\n"
    "    push rcx\n"
    "    push rdx\n"
    "    push rdi\n"
    "    mov dword [__cly_ready], 1\n"
    "    mov dx, 0x3F9\n"
    "    xor al, al\n"
    "    out dx, al\n"
    "    mov dx, 0x3FB\n"
    "    mov al, 0x80\n"
    "    out dx, al\n"
    "    mov dx, 0x3F8\n"
    "    mov al, 1\n"
    "    out dx, al\n"
    "    mov dx, 0x3F9\n"
    "    xor al, al\n"
    "    out dx, al\n"
    "    mov dx, 0x3FB\n"
    "    mov al, 3\n"
    "    out dx, al\n"
    "    mov dx, 0x3FA\n"
    "    mov al, 0xC7\n"
    "    out dx, al\n"
    "    mov dx, 0x3FC\n"
    "    mov al, 0x0B\n"
    "    out dx, al\n"
    "    mov edi, 0xB8000\n"
    "    mov ecx, 1000\n"
    "    mov eax, 0x07200720\n"
    "    cld\n"
    "    rep stosd\n"
    "    mov qword [__cly_cur], 0\n"
    "    pop rdi\n"
    "    pop rdx\n"
    "    pop rcx\n"
    "    pop rax\n"
    "    ret\n"
    "__cly_putc:\n"
    "    push rax\n"
    "    push rbx\n"
    "    push rcx\n"
    "    push rdx\n"
    "    push rsi\n"
    "    push rdi\n"
    "    movzx ebx, al\n"
    "    out 0xE9, al\n"
    "    mov dx, 0x3FD\n"
    "    mov ecx, 65536\n"
    ".w:\n"
    "    in al, dx\n"
    "    cmp al, 0xFF\n"
    "    je .vga\n"
    "    test al, 0x20\n"
    "    jnz .snd\n"
    "    dec ecx\n"
    "    jnz .w\n"
    "    jmp .vga\n"
    ".snd:\n"
    "    mov dx, 0x3F8\n"
    "    mov al, bl\n"
    "    out dx, al\n"
    ".vga:\n"
    "    mov rdi, [__cly_cur]\n"
    "    cmp bl, 10\n"
    "    je .nl\n"
    "    cmp bl, 13\n"
    "    je .cr\n"
    "    cmp bl, 8\n"
    "    je .bs\n"
    "    cmp bl, 9\n"
    "    je .tab\n"
    "    mov al, bl\n"
    "    mov ah, 7\n"
    "    mov [0xB8000+rdi*2], ax\n"
    "    inc rdi\n"
    "    jmp .chk\n"
    ".nl:\n"
    "    mov rax, rdi\n"
    "    xor edx, edx\n"
    "    mov ecx, 80\n"
    "    div rcx\n"
    "    sub rdi, rdx\n"
    "    add rdi, 80\n"
    "    jmp .chk\n"
    ".cr:\n"
    "    mov rax, rdi\n"
    "    xor edx, edx\n"
    "    mov ecx, 80\n"
    "    div rcx\n"
    "    sub rdi, rdx\n"
    "    jmp .chk\n"
    ".bs:\n"
    "    test rdi, rdi\n"
    "    jz .chk\n"
    "    dec rdi\n"
    "    mov word [0xB8000+rdi*2], 0x0720\n"
    "    jmp .chk\n"
    ".tab:\n"
    "    add rdi, 8\n"
    "    and rdi, -8\n"
    ".chk:\n"
    "    cmp rdi, 2000\n"
    "    jb .done\n"
    "    mov esi, 0xB80A0\n"
    "    mov edi, 0xB8000\n"
    "    mov ecx, 960\n"
    "    cld\n"
    "    rep movsd\n"
    "    mov ecx, 40\n"
    "    mov eax, 0x07200720\n"
    "    rep stosd\n"
    "    mov edi, 1920\n"
    ".done:\n"
    "    mov [__cly_cur], rdi\n"
    "    mov dx, 0x3D4\n"
    "    mov al, 0x0F\n"
    "    out dx, al\n"
    "    inc dx\n"
    "    mov eax, edi\n"
    "    out dx, al\n"
    "    dec dx\n"
    "    mov al, 0x0E\n"
    "    out dx, al\n"
    "    inc dx\n"
    "    mov eax, edi\n"
    "    shr eax, 8\n"
    "    out dx, al\n"
    "    pop rdi\n"
    "    pop rsi\n"
    "    pop rdx\n"
    "    pop rcx\n"
    "    pop rbx\n"
    "    pop rax\n"
    "    ret\n"
    "__cly_getc:\n"
    "    push rbx\n"
    "    push rcx\n"
    "    push rdx\n"
    ".poll:\n"
    "    mov dx, 0x3FD\n"
    "    in al, dx\n"
    "    cmp al, 0xFF\n"
    "    je .kbd\n"
    "    test al, 1\n"
    "    jz .kbd\n"
    "    mov dx, 0x3F8\n"
    "    in al, dx\n"
    "    movzx eax, al\n"
    "    cmp al, 13\n"
    "    jne .fin\n"
    "    mov al, 10\n"
    "    jmp .fin\n"
    ".kbd:\n"
    "    in al, 0x64\n"
    "    test al, 1\n"
    "    jz .poll\n"
    "    in al, 0x60\n"
    "    movzx ecx, al\n"
    "    cmp cl, 0x2A\n"
    "    je .shon\n"
    "    cmp cl, 0x36\n"
    "    je .shon\n"
    "    cmp cl, 0xAA\n"
    "    je .shoff\n"
    "    cmp cl, 0xB6\n"
    "    je .shoff\n"
    "    test cl, 0x80\n"
    "    jnz .poll\n"
    "    cmp cl, 0x39\n"
    "    ja .poll\n"
    "    cmp dword [__cly_shift], 0\n"
    "    je .norm\n"
    "    lea rbx, [__cly_ktab_s]\n"
    "    movzx eax, byte [rbx+rcx]\n"
    "    jmp .have\n"
    ".norm:\n"
    "    lea rbx, [__cly_ktab]\n"
    "    movzx eax, byte [rbx+rcx]\n"
    ".have:\n"
    "    test eax, eax\n"
    "    jz .poll\n"
    "    jmp .fin\n"
    ".shon:\n"
    "    mov dword [__cly_shift], 1\n"
    "    jmp .poll\n"
    ".shoff:\n"
    "    mov dword [__cly_shift], 0\n"
    "    jmp .poll\n"
    ".fin:\n"
    "    pop rdx\n"
    "    pop rcx\n"
    "    pop rbx\n"
    "    ret\n"
    "__cly_heapptr:\n"
    "    mov rax, [__cly_heap]\n"
    "    test rax, rax\n"
    "    jnz .r\n"
    "    mov rax, __cly_image_end\n"
    "    add rax, 4095\n"
    "    and rax, -4096\n"
    "    cmp rax, 0x100000\n"
    "    jae .r\n"
    "    mov eax, 0x100000\n"
    ".r:\n"
    "    ret\n"
    "__cly_alloc:\n"
    "    call __cly_heapptr\n"
    "    mov rbx, rax\n"
    "    mov rdi, rax\n"
    "    mov rcx, rdx\n"
    "    xor eax, eax\n"
    "    cld\n"
    "    rep stosb\n"
    "    lea rax, [rbx+rdx]\n"
    "    mov [__cly_heap], rax\n"
    "    mov rax, rbx\n"
    "    ret\n"
    "__cly_syscall:\n"
    "    push rbx\n"
    "    push rcx\n"
    "    push rdx\n"
    "    push rsi\n"
    "    push rdi\n"
    "    push rbp\n"
    "    cmp dword [__cly_ready], 0\n"
    "    jne .go\n"
    "    push rax\n"
    "    call __cly_init\n"
    "    pop rax\n"
    ".go:\n"
    "    cmp eax, 1\n"
    "    je .write\n"
    "    cmp eax, 0\n"
    "    je .read\n"
    "    cmp eax, 9\n"
    "    je .mmap\n"
    "    cmp eax, 12\n"
    "    je .brk\n"
    "    cmp eax, 11\n"
    "    je .zero\n"
    "    cmp eax, 3\n"
    "    je .zero\n"
    "    cmp eax, 24\n"
    "    je .zero\n"
    "    cmp eax, 39\n"
    "    je .getpid\n"
    "    cmp eax, 35\n"
    "    je .sleep\n"
    "    cmp eax, 60\n"
    "    je .exit\n"
    "    cmp eax, 231\n"
    "    je .exit\n"
    "    cmp eax, 16\n"
    "    je .notty\n"
    "    mov rax, -38\n"
    "    jmp .out\n"
    ".zero:\n"
    "    xor eax, eax\n"
    "    jmp .out\n"
    ".getpid:\n"
    "    mov eax, 1\n"
    "    jmp .out\n"
    ".notty:\n"
    "    mov rax, -25\n"
    "    jmp .out\n"
    ".ebadf:\n"
    "    mov rax, -9\n"
    "    jmp .out\n"
    ".write:\n"
    "    cmp edi, 1\n"
    "    jb .ebadf\n"
    "    cmp edi, 2\n"
    "    ja .ebadf\n"
    "    mov rcx, rdx\n"
    "    mov rbx, rdx\n"
    "    test rcx, rcx\n"
    "    jz .wdone\n"
    ".wl:\n"
    "    mov al, [rsi]\n"
    "    call __cly_putc\n"
    "    inc rsi\n"
    "    dec rcx\n"
    "    jnz .wl\n"
    ".wdone:\n"
    "    mov rax, rbx\n"
    "    jmp .out\n"
    ".read:\n"
    "    test edi, edi\n"
    "    jnz .ebadf\n"
    "    xor ebx, ebx\n"
    "    test rdx, rdx\n"
    "    jz .rdone\n"
    ".rl:\n"
    "    call __cly_getc\n"
    "    cmp al, 8\n"
    "    je .rbs\n"
    "    cmp al, 127\n"
    "    je .rbs\n"
    "    mov [rsi+rbx], al\n"
    "    inc rbx\n"
    "    call __cly_putc\n"
    "    cmp al, 10\n"
    "    je .rdone\n"
    "    cmp rbx, rdx\n"
    "    jb .rl\n"
    "    jmp .rdone\n"
    ".rbs:\n"
    "    test rbx, rbx\n"
    "    jz .rl\n"
    "    dec rbx\n"
    "    mov al, 8\n"
    "    call __cly_putc\n"
    "    mov al, 32\n"
    "    call __cly_putc\n"
    "    mov al, 8\n"
    "    call __cly_putc\n"
    "    jmp .rl\n"
    ".rdone:\n"
    "    mov rax, rbx\n"
    "    jmp .out\n"
    ".mmap:\n"
    "    mov rdx, rsi\n"
    "    add rdx, 4095\n"
    "    and rdx, -4096\n"
    "    call __cly_alloc\n"
    "    jmp .out\n"
    ".brk:\n"
    "    cmp qword [__cly_brkbase], 0\n"
    "    jne .b1\n"
    "    mov edx, 0x1000000\n"
    "    call __cly_alloc\n"
    "    mov [__cly_brkbase], rax\n"
    "    mov [__cly_brk], rax\n"
    ".b1:\n"
    "    test rdi, rdi\n"
    "    jz .b2\n"
    "    cmp rdi, [__cly_brkbase]\n"
    "    jb .b2\n"
    "    mov rax, [__cly_brkbase]\n"
    "    add rax, 0x1000000\n"
    "    cmp rdi, rax\n"
    "    ja .b2\n"
    "    mov [__cly_brk], rdi\n"
    ".b2:\n"
    "    mov rax, [__cly_brk]\n"
    "    jmp .out\n"
    ".sleep:\n"
    "    mov rax, [rdi+8]\n"
    "    xor edx, edx\n"
    "    mov ecx, 1000000\n"
    "    div rcx\n"
    "    mov rbx, rax\n"
    "    mov rax, [rdi]\n"
    "    imul rax, rax, 1000\n"
    "    add rbx, rax\n"
    "    imul rbx, rbx, 1000\n"
    ".s1:\n"
    "    test rbx, rbx\n"
    "    jz .zero\n"
    "    out 0x80, al\n"
    "    dec rbx\n"
    "    jmp .s1\n"
    ".exit:\n"
    "    mov eax, edi\n"
    "    out 0xF4, al\n"
    "    mov dx, 0x604\n"
    "    mov ax, 0x2000\n"
    "    out dx, ax\n"
    "    mov dx, 0xB004\n"
    "    out dx, ax\n"
    "    mov dx, 0x4004\n"
    "    mov ax, 0x3400\n"
    "    out dx, ax\n"
    "    cli\n"
    ".h:\n"
    "    hlt\n"
    "    jmp .h\n"
    ".out:\n"
    "    pop rbp\n"
    "    pop rdi\n"
    "    pop rsi\n"
    "    pop rdx\n"
    "    pop rcx\n"
    "    pop rbx\n"
    "    ret\n"
;
